### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by HenryKang1** [soulslicer/probabilistic-depth#1]
Hello. Thank you for the sharing code.
I want to test your algorithm in my project but is it require extra c++ library?
I try to compile the code and they request the Eigen library.
Thank you.

**Comment by soulslicer** [comment]
Yeah you will need that. 

sudo apt-get install libeigen3-dev

**Comment by HenryKang1** [comment]
> Yeah you will need that.
> 
> sudo apt-get install libeigen3-dev

Thank you.
